self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - byo-linux-x86_64-glibc-2.28
    - byo-clean-macos-12-aarch64
    - byo-clean-macos-12-x86_64
    - byo-clean-windows-10-22h2-x86_64
    - byo-clean-linux-x86_64-glibc-2.28
    - byo-hil-macos-aarch64
    - byo-hil-windows-x86_64
    - byo-hil-linux-x86_64

# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables: null

# Configuration for file paths. The keys are glob patterns to match to file
# paths relative to the repository root. The values are the configurations for
# the file paths. Note that the path separator is always '/'.
# The following configurations are available.
#
# "ignore" is an array of regular expression patterns. Matched error messages
# are ignored. This is similar to the "-ignore" command line option.
paths:
#  .github/workflows/**/*.yml:
#    ignore: []
